In [1]:
import numpy as np
import cv2

In [7]:
img = cv2. imread('simpson.jpeg')

print (img.shape)
print (img.size)
print (img.dtype)

b,g,r = cv2.split(img)
print (" ")
print ('blue channel = ',b)
print (" ")
print ('green channel = ',g)
print (" ")
print ('red channel = ',r)
print("")

# we can merge this colors and create img

img =cv2.merge((b,g,r))
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(552, 980, 3)
1622880
uint8
 
blue channel =  [[118 118 118 ... 118 118 118]
 [118 118 118 ... 118 118 118]
 [118 118 118 ... 118 118 118]
 ...
 [ 84  83  81 ...  65  65  65]
 [ 84  83  81 ...  63  63  63]
 [ 84  83  81 ...  63  63  63]]
 
green channel =  [[50 50 50 ... 50 50 50]
 [50 50 50 ... 50 50 50]
 [50 50 50 ... 50 50 50]
 ...
 [20 19 19 ... 18 18 18]
 [20 19 19 ... 18 18 18]
 [20 19 19 ... 18 18 18]]
 
red channel =  [[21 21 21 ... 21 21 21]
 [21 21 21 ... 21 21 21]
 [21 21 21 ... 21 21 21]
 ...
 [15 14 13 ... 14 14 14]
 [15 14 13 ... 14 14 14]
 [15 14 13 ... 14 14 14]]



In [12]:
# copied from image and adding to another part

copied_part = img[200:250, 250:350]

# adding part
img[400:450, 400:500] = cropped_part
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
# adding two image together. WARNING : image sizes should be matchable. so use resize thing.
img = cv2. imread('simpson.jpeg')
img2 = cv2.imread('randomlogo.png')


img = cv2.resize(img,(512,512))
img2 = cv2.resize(img2, (512,512))

dst = cv2.add(img,img2)


cv2.imshow('image',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# we can tune the weights of the images which we are going to add each other.

img = cv2. imread('simpson.jpeg')
img2 = cv2.imread('randomlogo.png')


img = cv2.resize(img,(512,512))
img2 = cv2.resize(img2, (512,512))

dst = cv2.addWeighted(img, .9, img2, .1, 0)


cv2.imshow('image',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()